name: Master Branch

on:
  push:
    branches: [ autoCursor ]
  pull_request:
    branches: [ autoCursor ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: "adopt"
        java-version: 11

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Create debug build
      uses: gradle/gradle-build-action@v1
      with:
        distributions-cache-enabled: true
        dependencies-cache-enabled: true
        configuration-cache-enabled: true
        arguments: build

    - name: Set outputs
      id: vars
      run: |
        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
        echo "::set-output name=apk_path::$(find build/outputs/apk/debug/*.apk)"

    - name: Get apk info
      id: apk-info
      uses: hkusu/apk-info-action@v1
      with:
        apk-path: ${{ steps.vars.outputs.apk_path }}

    - name: Output apk version code
      run: |
        export VERSION_CODE="${{ steps.apk-info.outputs.version-code }}"
        echo "{\"version_code\": $VERSION_CODE}" > info.json
        unset VERSION_CODE

    - name: Upload binaries to a release
      uses: softprops/action-gh-release@v1
      with:
        body: ${{ github.event.head_commit.message }}
        files: |
          info.json
          ${{ steps.vars.outputs.apk_path }}
        tag_name: ${{ steps.vars.outputs.sha_short }}

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: osu-droid-debug
        path: ${{ steps.vars.outputs.apk_path }}
